version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5433:5433'
    command: -p 5433
    environment:
      - POSTGRES_USER=earnipay
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=earnipayDb
